#!/bin/zsh

# https://wiki.archlinux.org/title/Screen_capture#Wayland

help='
  Usage:
  \tscreencap [options]

  Options:
  \t-r, --rect            \t Select a rect region to take screenshot
  \t-w, --window          \t Take screenshot of the current active window
  \t-f, --full            \t Take fullscreen shot
  \t-s, --save [path]     \t Save the screenshot file, default to ~/Pictores/screenshots
'

if [[ $# -eq 0 ]]; then
    echo $help
    exit
fi

MODE=false
for i in $@; do
    # rect
    if [[ $i =~ '^(-r|--rect)$' ]]; then
        img=$(slurp | grim -g - -)
        MODE=true
        break
    elif [[ $i =~ '^(-w|--window)$' ]]; then
        img=$(hyprctl -j activewindow | jq -r '"\(.at[0]),\(.at[1] \(.size[0]x\(.size[1])"' | grim -g - -)
        MODE=true
        break
    elif [[ $i =~ '^(-f|--full)$' ]]; then
        img=$(grim -)
        MODE=true
        break
    fi
done

if ! $MODE; then
    echo $help
    exit
fi

for ((i=1;i<=$#;i++)); do
    ARG=$@[$i]
    if [[ $ARG =~ '^(-s|--save)$' ]]; then
        SAVE=$((i + 1))
    else
    fi
done

echo $SAVE
if [[ -z $SAVE ]]; then
    echo $img | wl-copy
else
    ARG_OUT=$@[$SAVE]
    if [[ -z $ARG_OUT ]]; then
        DIR=~/Pictures/screenshots
    else
        DIR=$ARG_OUT
    fi
    OUT=$DIR/screenshot-`date +"%Y-%m-%d_%H_%M_%S.%N"`.png
    mkdir -p $DIR
    echo $img > $OUT
fi
